### PR TITLE
Warnings fixes

### PR DESCRIPTION
**Pull request by Wohlstand**

### CODE REVIEW

**Comment by rversteegen** [comment]
Thanks. Unfortunately I had a commit that I hadn't pushed, so there are a bunch of conflicts. I'm working on merging it.

**Comment by Wohlstand** [comment]
Myself I trying to solve colflict too now

**Comment by Wohlstand** [comment]
Okay, I need to redo my warning fix job from scratch 😋 
One hint: The warnings I have catched and fixed in the Qt Creator when CLang Code Model is turned on, you will be able to see them.

**Comment by rversteegen** [comment]
Oh! Well, if you want to; I didn't get far, and it's Christmas Day, so I better go...
I guess with all the new structures, even if I merged everything, there might be quite different warnings.

I don't have Qt Creator installed, have never used Qt, but I do have clang, I ought to get into the habit of using its static analyzer.

**Comment by Wohlstand** [comment]
One thing I see:
default

This means a thing will fail on older C than C99 / C11 or C++11 or on other compilers like clunky MSVC family.
Anyway I think I have something to avoid this and keep features work right

**Comment by Wohlstand** [comment]
Just an off-topic:
Myself I use Qt Creator IDE for non-Qt projects too: it is more lightweight than MSVC (I never liked even before I learned about Qt and Qt Creator IDE) convenient and has lot of built-in features such as refactoring (smart renaming of C++ object and not a silly string-replace!, move implementation between header and cpp and in-class out-class, etc.), usage search, etc. Qt Creator is able to use how Qmake projects (pro) and CMake too (myself for now I graduately moving to CMake away from QMake).

**Comment by Wohlstand** [comment]
Conflicts has been fixed!
I did the force push to drop away my changes and put your state as base

**Comment by rversteegen** [comment]
Oh, I didn't realise that anonymous structs weren't added until C11, and apparently still aren't in C++. But apparently gcc and clang now both accept anonymous structs when targetting any C or C++ version without warning, unless you pass -pedantic. Also, I tried compiling with MSVC 2010 and it didn't even show a warning for this*. Therefore, I think it's better to just leave it as it is rather than make the code messier just to please the static analyzer.

* However MSVC does show a very worrying warning
` warning C4146: unary minus operator applied to unsigned type, result still unsigned`
for lines like
`                pix7.r += GifIMax( -pix7.r, r_err * 7 / 16 );`
Why doesn't clang show a warning for this? One or the other must be wrong! Maybe MSVC is miscompiling this, and is meant to promote pix7.r to a larger signed type?

Personally I use emacs, but emacs doesn't come with any C++ refactoring features. I would be willing to use Qt Creator just when I have to do some refactoring, so thanks for the tip, I'll have a look.

**Comment by rversteegen** [comment]
Thanks! Adding a 'comp' method does seem to be the best standards-compliant way to work around lack of anonymous structs.

**Comment by Wohlstand** [comment]
Emacs is too generic editor just is like to xed, GEdit, Kate, Akelpad, Notepad++, etc. and any warnings / refactorings, etc. are rarely appears as extensions. The Qt Creator is a C++-specific IDE which provides specific to C++ features.

**Comment by rversteegen** [comment]
Really, emacs is a lisp IDE which was extended into a generic text editor, but I deal with obscure languages so like the ability to write my own modes and extensions :)

**Pull request merged**
