### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by Daniel-Cortez**
Fixed a bunch of warnings issued by GCC and Clang. Most of them were caused by macros `GIF_ASSERT` and `GIF_STATS` (f.e. GCC turns `GIF_ASSERT(expr);` into `;`, and then complains because of an extra semicolon).

### CODE REVIEW

**Comment by Daniel-Cortez** [comment]
I think there's also a couple of other things worth noting:
1. The `GIF_ASSERT` macro is defined as empty, but `assert.h` was #included anyway. For this PR I decided to play it safe and just removed the line with unused inclusion, but maybe it would be better to do the opposite by redefining `GIF_ASSERT` as `assert`?
```C
#ifndef GIF_ASSERT
#include <assert.h> // move the inclusion line from the very top of the file here
#define GIF_ASSERT assert
#endif
```

2. There's an unused parameter in `GifMakePalette` called `buildForDither`. Is it planned to be used later, or is it just a leftover from the previous changes? (Judging from the commit history the latter seems to be the case but I may be wrong.)

**Comment by rversteegen** [comment]
Whoops, I haven't been compiling with extra warnings enabled! Thanks.
Yes, `buildForDither` can just be cut; if I do want it in future it can just be put back later.
I should probably have written `#define GIF_ASSERT assert` in the first place.

**Comment by Daniel-Cortez** [comment]
> Whoops, I haven't been compiling with extra warnings enabled!

I haven't used any extra warnings either. The warnings I fixed were just regular warnings issued by GCC and Clang, without `-Wextra`.

> I should probably have written #define GIF_ASSERT assert in the first place.

Please feel free to use the snippet I provided in the above post, it's not worth of making a separate PR anyway.

**Comment by rversteegen** [comment]
Odd, I only saw the warnings you mentioned when compiling with `-Wall -Wextra -Wpendantic`, but not with `-Wall`. Using GCC 8.2.0.

**Comment by Daniel-Cortez** [comment]
Guess GCC doesn't show these warnings by default in the newer versions then; I was using GCC 4.9.2 and Clang 3.5.0.
Also, was leaving the `#define GIF_ASSERT(x) (void)0` line in the latest commit intentional?

**Comment by rversteegen** [comment]
Oh, yes, I left that there so you can enable asserts in the rest of the program without enabling them in gif.h... but maybe that doesn't make too much sense?

**Comment by Daniel-Cortez** [comment]
If your intention was to disable `GIF_ASSERT` by default, then what was the point in adding an `#ifndef GIF_ASSERT` block after that line? It will never work since `GIF_ASSERT` is already defined before it as `(void)0`.

**Pull request merged**
